travis:
  secure:
    BINSTAR_TOKEN: FG+p5tkE4qbg1Sb1okTjJREmySHy/fuClRvej3rueCt5x8/KvBsN0nqyRLsXP2q5UZ7aLO+o0WrpokDyZonmTGMKSFPZLgNmpHXfbIEuwrCVF9Mj996ogW9r/dxKgGQX0sJPupjw/0Exyb6ktQWZXEz61h1JDoj/Qvs4mCHthh+AVhFTRWh5oRz7n7wlvnQWBX8mAc0XBZZ/NGfLG7Ro2QIiRtv+g+WLWvsuKZDrcJe7QU1OFPox3KbNMl/sBtIhsmROKQ3wMfY7aouzaNaMGxfcFwGWVjnbh6/OfFv9ped5BUgCV/KmbionYA8nCKEoUPnI/8wgVf8npMHrJ9DXJNPvaXJzY4j603RgQEd2kkd/NvPDwYtUAxyWbQxoguYOaMPEozrKTkX4EWHz0HGySUiUZwZBTrn0hPQRZhdJaQIprocFIX+7SGNkkGVS2wOI+/OEQwHH6vx149h7dkN3wgSzaMWLIVY0eDctGVR9a5koI/eKJqfmeFhB/urdn+B8agwzit6PlGoJuXAniP9MXJ2+vuG7AZ2wFzQ4o8TIZpLaPLLOhOZzrpRa2iKouFtrwxLHXs4NlwYiRyVVPJ32I9EwpQq3QdITWa3fT+FVY2Avl4WUEcziX78RQ2hzgtgrl4y/gZeYuVAsVydfg1jCiXIbpF6gsKC+B2zNLuoWcD8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
