travis:
  secure:
    BINSTAR_TOKEN: fbOtm0iQu0t6KZUqIljzKKI+Yga4dege/GkKPFaeNPIxzJUP/W8ttdQsgtKb4gJ+Ta1A39SxdRSosA98Kx/5vzH/jfStJJfyOmKpx9EvWHuT10jnrd0WOuzfMrt0h3Pa9x031kZqlXRqJVOMLm/iRFppgHcZLnv2a+GG2opewqlw5XJgeSlw+sLvTf6oGgAp4kKHCOPNRBLpnPHO09KptOhZpZwzf0lvdNsmGV1dEyL+VxEjo2tBpyvXSAhnmWg4Yjai9PIMiAGHb/FgPxbvDP7JUkMKsbVPB5CRSXt7Zrcj3y0Xn7VlsURCmFsMCKwIvrAf2DtAuKCQbegu0ItFfIAz8P6biCYB6tVuMTcvBg6fGB3lWvxaRYzhJzeu04g4a01zqSkNiAH5GJw2inBjD72+69ilcsYODwFwvtC/O/U3cEl+4xpVBDJNyO8dNCPZiaTVkz6K8Vc0cUi254HAHdFXFuamxcDOCpLbgK2iNi0vDoDnXb5iVvW9RTiV5eyBSJjmSeqNx08rsrMaftOC/+Jo21jRShJg0ONwRyZjBs+i3c+T6N0WjuT3bqOdQt7iNvwFrIeVJ8wMhzo3dcCbrULfqJm9JNYBQ4rezHsUjLxnBbrSafcksd3uSPL7v/WAQvlF71W1fcyfV3wyAzUn+UVl9RXKkXqrt07/TPlOUuU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
